/**
 * Iconos de Avatar - Estilo Neo Brutalism 🎨
 * 45+ iconos súper divertidos y creativos para Delicrunch
 * Cada icono tiene: id, icon, iconSet, color, backgroundColor, label, category
 */

export const PROFILE_AVATARS = [
  // === COMIDA DIVERTIDA (12) ===
  { 
    id: 'pizza', 
    icon: 'pizza', 
    iconSet: 'ionicons',
    color: '#FF6B35', 
    backgroundColor: '#FFF3E0',
    label: '🍕 Pizza',
    category: 'food',
  },
  { 
    id: 'burger', 
    icon: 'food', 
    iconSet: 'material',
    color: '#8D6E63', 
    backgroundColor: '#FFEBCC',
    label: '🍔 Hamburguesa',
    category: 'food',
  },
  { 
    id: 'taco', 
    icon: 'taco', 
    iconSet: 'material',
    color: '#FFB300', 
    backgroundColor: '#FFF8E1',
    label: '🌮 Taco',
    category: 'food',
  },
  { 
    id: 'croissant', 
    icon: 'food-croissant', 
    iconSet: 'material',
    color: '#D4A373', 
    backgroundColor: '#FFF5E8',
    label: '🥐 Croissant',
    category: 'food',
  },
  { 
    id: 'apple', 
    icon: 'food-apple', 
    iconSet: 'material',
    color: '#E53935', 
    backgroundColor: '#FFEBEE',
    label: '🍎 Manzana',
    category: 'food',
  },
  { 
    id: 'cupcake', 
    icon: 'cupcake', 
    iconSet: 'material',
    color: '#FF69B4', 
    backgroundColor: '#FFE5F1',
    label: '🧁 Cupcake',
    category: 'food',
  },
  { 
    id: 'donut', 
    icon: 'food-variant', 
    iconSet: 'material',
    color: '#FF1744', 
    backgroundColor: '#FFDEE9',
    label: '🍩 Dona',
    category: 'food',
  },
  { 
    id: 'cake', 
    icon: 'cake-variant', 
    iconSet: 'material',
    color: '#9C27B0', 
    backgroundColor: '#F3E5F5',
    label: '🍰 Pastel',
    category: 'food',
  },
  { 
    id: 'noodles', 
    icon: 'noodles', 
    iconSet: 'material',
    color: '#FFD54F', 
    backgroundColor: '#FFFDE7',
    label: '🍜 Fideos',
    category: 'food',
  },
  { 
    id: 'ice_cream', 
    icon: 'ice-cream', 
    iconSet: 'ionicons',
    color: '#FF6EC7', 
    backgroundColor: '#FFE5F5',
    label: '🍦 Helado',
    category: 'food',
  },
  { 
    id: 'sushi', 
    icon: 'food-variant', 
    iconSet: 'material',
    color: '#FF5252', 
    backgroundColor: '#FFE8E8',
    label: '🍣 Sushi',
    category: 'food',
  },
  { 
    id: 'hotdog', 
    icon: 'food-hot-dog', 
    iconSet: 'material',
    color: '#FF6F00', 
    backgroundColor: '#FFF3E0',
    label: '🌭 Hot Dog',
    category: 'food',
  },

  // === BEBIDAS REFRESCANTES (8) ===
  { 
    id: 'coffee', 
    icon: 'cafe', 
    iconSet: 'ionicons',
    color: '#6F4E37', 
    backgroundColor: '#F5E6D3',
    label: '☕ Café',
    category: 'drinks',
  },
  { 
    id: 'tea', 
    icon: 'tea', 
    iconSet: 'material',
    color: '#8BC34A', 
    backgroundColor: '#F1F8E9',
    label: '🍵 Té',
    category: 'drinks',
  },
  { 
    id: 'cocktail', 
    icon: 'glass-cocktail', 
    iconSet: 'material',
    color: '#FF4081', 
    backgroundColor: '#FFE8F1',
    label: '🍹 Cóctel',
    category: 'drinks',
  },
  { 
    id: 'beer', 
    icon: 'beer', 
    iconSet: 'ionicons',
    color: '#FFA000', 
    backgroundColor: '#FFF8E1',
    label: '🍺 Cerveza',
    category: 'drinks',
  },
  { 
    id: 'wine', 
    icon: 'wine', 
    iconSet: 'ionicons',
    color: '#7B1FA2', 
    backgroundColor: '#F3E5F5',
    label: '🍷 Vino',
    category: 'drinks',
  },
  { 
    id: 'smoothie', 
    icon: 'cup', 
    iconSet: 'material',
    color: '#FF9800', 
    backgroundColor: '#FFF3E0',
    label: '🥤 Smoothie',
    category: 'drinks',
  },
  { 
    id: 'bubble_tea', 
    icon: 'cup-water', 
    iconSet: 'material',
    color: '#9C27B0', 
    backgroundColor: '#F3E5F5',
    label: '🧋 Bubble Tea',
    category: 'drinks',
  },
  { 
    id: 'juice', 
    icon: 'bottle-tonic-plus', 
    iconSet: 'material',
    color: '#FF9800', 
    backgroundColor: '#FFF3E0',
    label: '🧃 Jugo',
    category: 'drinks',
  },

  // === CHEF & COCINA (8) ===
  { 
    id: 'chef_hat', 
    icon: 'chef-hat', 
    iconSet: 'material',
    color: '#FFFFFF', 
    backgroundColor: '#263238',
    label: '👨‍🍳 Chef',
    category: 'kitchen',
  },
  { 
    id: 'pot', 
    icon: 'pot-steam', 
    iconSet: 'material',
    color: '#607D8B', 
    backgroundColor: '#ECEFF1',
    label: '🍲 Olla',
    category: 'kitchen',
  },
  { 
    id: 'frying_pan', 
    icon: 'frying-pan', 
    iconSet: 'material',
    color: '#455A64', 
    backgroundColor: '#CFD8DC',
    label: '🍳 Sartén',
    category: 'kitchen',
  },
  { 
    id: 'knife', 
    icon: 'knife', 
    iconSet: 'material',
    color: '#546E7A', 
    backgroundColor: '#ECEFF1',
    label: '🔪 Cuchillo',
    category: 'kitchen',
  },
  { 
    id: 'silverware', 
    icon: 'silverware-fork-knife', 
    iconSet: 'material',
    color: '#9E9E9E', 
    backgroundColor: '#F5F5F5',
    label: '🍴 Cubiertos',
    category: 'kitchen',
  },
  { 
    id: 'blender', 
    icon: 'blender', 
    iconSet: 'material',
    color: '#26A69A', 
    backgroundColor: '#E0F2F1',
    label: '🥣 Licuadora',
    category: 'kitchen',
  },
  { 
    id: 'coffee_maker', 
    icon: 'coffee-maker', 
    iconSet: 'material',
    color: '#795548', 
    backgroundColor: '#EFEBE9',
    label: '☕ Cafetera',
    category: 'kitchen',
  },
  { 
    id: 'mixing_bowl', 
    icon: 'bowl-mix', 
    iconSet: 'material',
    color: '#42A5F5', 
    backgroundColor: '#E3F2FD',
    label: '🥗 Bowl',
    category: 'kitchen',
  },

  // === ANIMALES TIERNOS (10) ===
  { 
    id: 'cat', 
    icon: 'cat', 
    iconSet: 'material',
    color: '#FF9800', 
    backgroundColor: '#FFF3E0',
    label: '🐱 Gatito',
    category: 'animals',
  },
  { 
    id: 'dog', 
    icon: 'dog', 
    iconSet: 'material',
    color: '#8D6E63', 
    backgroundColor: '#EFEBE9',
    label: '🐶 Perrito',
    category: 'animals',
  },
  { 
    id: 'panda', 
    icon: 'panda', 
    iconSet: 'material',
    color: '#212121', 
    backgroundColor: '#F5F5F5',
    label: '🐼 Panda',
    category: 'animals',
  },
  { 
    id: 'pig', 
    icon: 'pig', 
    iconSet: 'material',
    color: '#F48FB1', 
    backgroundColor: '#FCE4EC',
    label: '🐷 Cerdito',
    category: 'animals',
  },
  { 
    id: 'turtle', 
    icon: 'tortoise', 
    iconSet: 'material',
    color: '#4CAF50', 
    backgroundColor: '#E8F5E9',
    label: '🐢 Tortuga',
    category: 'animals',
  },
  { 
    id: 'penguin', 
    icon: 'penguin', 
    iconSet: 'material',
    color: '#263238', 
    backgroundColor: '#CFD8DC',
    label: '🐧 Pingüino',
    category: 'animals',
  },
  { 
    id: 'owl', 
    icon: 'owl', 
    iconSet: 'material',
    color: '#795548', 
    backgroundColor: '#EFEBE9',
    label: '🦉 Búho',
    category: 'animals',
  },
  { 
    id: 'fish', 
    icon: 'fish', 
    iconSet: 'ionicons',
    color: '#03A9F4', 
    backgroundColor: '#E1F5FE',
    label: '🐠 Pez',
    category: 'animals',
  },
  { 
    id: 'bee', 
    icon: 'bee', 
    iconSet: 'material',
    color: '#FFC107', 
    backgroundColor: '#FFF8E1',
    label: '🐝 Abeja',
    category: 'animals',
  },
  { 
    id: 'butterfly', 
    icon: 'butterfly', 
    iconSet: 'material',
    color: '#E91E63', 
    backgroundColor: '#FCE4EC',
    label: '🦋 Mariposa',
    category: 'animals',
  },

  // === ECO & PLANETA (7) ===
  { 
    id: 'leaf', 
    icon: 'leaf', 
    iconSet: 'ionicons',
    color: '#4CAF50', 
    backgroundColor: '#E8F5E9',
    label: '🌿 Hoja',
    category: 'eco',
  },
  { 
    id: 'earth', 
    icon: 'earth', 
    iconSet: 'ionicons',
    color: '#2196F3', 
    backgroundColor: '#E3F2FD',
    label: '🌍 Planeta',
    category: 'eco',
  },
  { 
    id: 'recycle', 
    icon: 'recycle', 
    iconSet: 'material',
    color: '#00BCD4', 
    backgroundColor: '#E0F7FA',
    label: '♻️ Reciclar',
    category: 'eco',
  },
  { 
    id: 'tree', 
    icon: 'tree', 
    iconSet: 'ionicons',
    color: '#66BB6A', 
    backgroundColor: '#E8F5E9',
    label: '🌳 Árbol',
    category: 'eco',
  },
  { 
    id: 'flower', 
    icon: 'flower', 
    iconSet: 'ionicons',
    color: '#FF4081', 
    backgroundColor: '#FCE4EC',
    label: '🌸 Flor',
    category: 'eco',
  },
  { 
    id: 'sprout', 
    icon: 'sprout', 
    iconSet: 'material',
    color: '#8BC34A', 
    backgroundColor: '#F1F8E9',
    label: '🌱 Brote',
    category: 'eco',
  },
  { 
    id: 'bag_eco', 
    icon: 'bag-handle', 
    iconSet: 'ionicons',
    color: '#689F38', 
    backgroundColor: '#F1F8E9',
    label: '🛍️ Bolsa Eco',
    category: 'eco',
  },

  // === DIVERSIÓN & EMOCIONES (8) ===
  { 
    id: 'heart', 
    icon: 'heart', 
    iconSet: 'ionicons',
    color: '#E91E63', 
    backgroundColor: '#FCE4EC',
    label: '❤️ Amor',
    category: 'fun',
  },
  { 
    id: 'sparkles', 
    icon: 'sparkles', 
    iconSet: 'ionicons',
    color: '#FFC107', 
    backgroundColor: '#FFF8E1',
    label: '✨ Brillos',
    category: 'fun',
  },
  { 
    id: 'star', 
    icon: 'star', 
    iconSet: 'ionicons',
    color: '#FDD835', 
    backgroundColor: '#FFFDE7',
    label: '⭐ Estrella',
    category: 'fun',
  },
  { 
    id: 'trophy', 
    icon: 'trophy', 
    iconSet: 'ionicons',
    color: '#FFB300', 
    backgroundColor: '#FFF8E1',
    label: '🏆 Trofeo',
    category: 'fun',
  },
  { 
    id: 'rocket', 
    icon: 'rocket', 
    iconSet: 'ionicons',
    color: '#FF5722', 
    backgroundColor: '#FFE8E0',
    label: '🚀 Cohete',
    category: 'fun',
  },
  { 
    id: 'balloon', 
    icon: 'balloon', 
    iconSet: 'ionicons',
    color: '#FF4081', 
    backgroundColor: '#FCE4EC',
    label: '🎈 Globo',
    category: 'fun',
  },
  { 
    id: 'gift', 
    icon: 'gift', 
    iconSet: 'ionicons',
    color: '#E91E63', 
    backgroundColor: '#FCE4EC',
    label: '🎁 Regalo',
    category: 'fun',
  },
  { 
    id: 'diamond', 
    icon: 'diamond', 
    iconSet: 'ionicons',
    color: '#00BCD4', 
    backgroundColor: '#E0F7FA',
    label: '💎 Diamante',
    category: 'fun',
  },
];

// Categorías de iconos actualizadas
export const AVATAR_CATEGORIES = [
  { id: 'all', label: 'Todos', icon: 'apps' },
  { id: 'food', label: 'Comida', icon: 'fast-food' },
  { id: 'drinks', label: 'Bebidas', icon: 'cafe' },
  { id: 'kitchen', label: 'Cocina', icon: 'restaurant' },
  { id: 'animals', label: 'Animales', icon: 'paw' },
  { id: 'eco', label: 'Eco', icon: 'leaf' },
  { id: 'fun', label: 'Diversión', icon: 'happy' },
];

// Obtener avatar por ID
export const getAvatarById = (id) => {
  return PROFILE_AVATARS.find(a => a.id === id) || PROFILE_AVATARS[0];
};

// Filtrar avatares por categoría
export const getAvatarsByCategory = (category) => {
  if (category === 'all') return PROFILE_AVATARS;
  return PROFILE_AVATARS.filter(a => a.category === category);
};

// Avatar por defecto (pizza divertida)
export const DEFAULT_AVATAR = PROFILE_AVATARS[0];

export default {
  PROFILE_AVATARS,
  AVATAR_CATEGORIES,
  getAvatarById,
  getAvatarsByCategory,
  DEFAULT_AVATAR,
};
